import { Typography } from "@mui/material";
import CalendarContainer from "./components/calendarContainer";
import { Box, Container } from "@mui/system";
import DateProvider from "./providers/dateProvider";

export default function Home() {
  return (
    <>
      <head>
        <title>Lesson Scheduler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <main>
        <DateProvider>
          <Container sx={{ width: "80%", mx: "auto", textAlign: "center" }}>
            <Typography variant="h3" sx={{ mx: "auto" }}>
              Lesson Scheduler
            </Typography>
            <CalendarContainer />
          </Container>
        </DateProvider>
      </main>
    </>
  );
}
