import { Typography } from "@mui/material";
import Scheduler from "./components/scheduler";
import Dashboard from "./components/dashboard";
import { Box, Container } from "@mui/system";
import DateProvider from "./providers/dateProvider";
import NavBar from "./components/navbar";
import UserProvider from "./providers/userProvider";

export default function Home() {
  return (
    <>
      <head>
        <title>Lesson Scheduler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <main>
        <DateProvider>
          <UserProvider>
            <Container sx={{ width: "80%", mx: "auto", textAlign: "center" }}>
              <Typography variant="h3" sx={{ mx: "auto" }}>
                Lesson Scheduler
              </Typography>
              <NavBar />
              {/* <Scheduler /> */}
              <Dashboard />
            </Container>
          </UserProvider>
        </DateProvider>
      </main>
    </>
  );
}
